#!/usr/bin/env bash
#
# Fix the "npm ci can only install when package.json and package-lock.json are in
# sync / Missing: <pkg> from lock file" error that appears during the Docker build.
#
# WHY THIS HAPPENS
#   Your machine runs a newer npm (e.g. npm 11) than the Docker image
#   (node:20-alpine ships npm 10). The two npm versions resolve the dependency tree
#   slightly differently, so a lock file generated locally can be rejected as
#   "out of sync" by `npm ci` inside the image. Running `npm install` again on your
#   machine cannot fix it — the lock must be generated by the SAME npm the image uses.
#
# WHAT THIS DOES
#   Regenerates frontend/package-lock.json *inside* the node:20-alpine image, then
#   verifies it with `npm ci --dry-run` in that same image. It uses
#   --package-lock-only, so it rewrites ONLY the lock file and never replaces your
#   local node_modules with Linux binaries.
#
# USAGE
#   From the repo root:   ./frontend/sync-lock.sh
#   From frontend/:       ./sync-lock.sh
#   Or via npm:           npm run lock:sync     (inside frontend/)
#
#   Then review and commit the lock file:
#     git add frontend/package-lock.json
#     git commit -m "chore: sync frontend lockfile for node:20-alpine (npm 10)"
#
# REQUIREMENTS: Docker Desktop running.

set -euo pipefail

# Resolve to the frontend directory no matter where this is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Keep this in sync with frontend/Dockerfile's `FROM node:<...>-alpine` line.
IMAGE="node:20-alpine"

# MSYS_NO_PATHCONV stops Git Bash on Windows from mangling the -v/-w paths.
run_in_image() {
  MSYS_NO_PATHCONV=1 docker run --rm -v "$PWD:/app" -w /app "$IMAGE" "$@"
}

echo "==> Regenerating package-lock.json inside $IMAGE (the npm the Docker build uses)..."
run_in_image npm install --package-lock-only --no-audit --no-fund

echo "==> Verifying with 'npm ci --dry-run' inside $IMAGE..."
run_in_image npm ci --dry-run --no-audit --no-fund >/dev/null

echo
echo "package-lock.json is now in sync with $IMAGE."
echo "Next:"
echo "    git add frontend/package-lock.json"
echo "    git commit -m \"chore: sync frontend lockfile for node:20-alpine (npm 10)\""
echo "Then re-run ./dev.sh"
